Repository JasonXu314/gitaway, pull requests merged in 2023-06, with the labels that each got.

#24 test event 2 in Paris
  2023-06-21_Paris_test_event_2.md
Labels: 🎡 Activity, 🚶 Low Exertion, ♿ Accessible, 💰 Expensive, 🧒 Child Friendly, 💵 Cash Only

#26 expired 2 in Paris
  2023-06-14_Paris_expired_2.md
Labels: 🎡 Activity, 🚴‍♂️ Medium Exertion, ♿ Accessible, 💵 Cash Only

#27 WaffleAir Excursion in Paris
  2023-06-24_Paris_WaffleAir_Excursion.md
Labels: 🎡 Activity, 🚶 Low Exertion, ♿ Accessible, 💲 Inexpensive, 🧒 Child Friendly

#34 whatever to do in san fran in san fran
  2023-06-13_san_fran_whatever_to_do_in_san_fran.md
Labels: 🎡 Activity, 🏔️ High Exertion, ♿ Accessible, 💲 Inexpensive

#41 json in Hamburg am Mainz
  2023-01-01_Hamburg_am_Mainz_json.md
Labels: 🎡 Activity, ♿ Accessible, 🧒 Child Friendly, 💵 Cash Only

#42 actually a new activity in Hamburg am Mainz
  2025-11-11_Hamburg_am_Mainz_actually_a_new_activity.md
Labels: 🎡 Activity, ♿ Accessible, 🧒 Child Friendly, 💵 Cash Only

#43 a name that has not been used before in Paris
  2024-02-01_Paris_a_name_that_has_not_been_used_before.md
Labels: 🎡 Activity, ♿ Accessible, 🧒 Child Friendly, 💵 Cash Only

#44 HHH in Hamburg am Mainz
  2023-08-20_Hamburg_am_Mainz_HHH.md
Labels: 🎡 Activity, 💵 Cash Only

#46 Explore old town in Munich, Germany
  2023-08-06_Munich,_Germany_Explore_old_town.md
Labels: 🎡 Activity, ♿ Accessible, 🧒 Child Friendly
